// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using RulesEngineEditor.Server.Business.Entities.Models;

namespace RulesEngineEditor.Server.Business.Entities.Models
{
    public partial class RulesEngineEditorContext
    {

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
