// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using RulesEngineEditor.Server.Business.Entities.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace RulesEngineEditor.Server.Business.Entities.Models
{
    public partial class RulesEngineEditorContext
    {
        private IRulesEngineEditorContextProcedures? _procedures;

        public virtual IRulesEngineEditorContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new RulesEngineEditorContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IRulesEngineEditorContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class RulesEngineEditorContextProcedures : IRulesEngineEditorContextProcedures
    {
        private readonly RulesEngineEditorContext _context;

        public RulesEngineEditorContextProcedures(RulesEngineEditorContext context)
        {
            _context = context;
        }
    }
}
