// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RulesEngineEditor.Server.Business.Entities.Models;

[Index("WorkflowDefinitionId", Name = "IX_WorkflowTestScenarios_WorkflowId")]
public partial class WorkflowTestScenarios
{
    [Key]
    public int ScenarioId { get; set; }

    public int WorkflowDefinitionId { get; set; }

    [StringLength(255)]
    public string ScenarioName { get; set; } = null!;

    [Column(TypeName = "json")]
    public string MockInputJson { get; set; } = null!;

    [Column(TypeName = "json")]
    public string? ExpectedOutputJson { get; set; }

    public DateTime? CreatedAt { get; set; }
}