// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RulesEngineEditor.Server.Business.Entities.Models;

[Index("WorkflowName", "Status", Name = "IX_WorkflowDefinitions_Name_Status")]
[Index("WorkflowName", "Version", Name = "UQ_Workflow_Version", IsUnique = true)]
public partial class WorkflowDefinitions
{
    [Key]
    public int WorkflowDefinitionId { get; set; }

    [StringLength(255)]
    public string WorkflowName { get; set; } = null!;

    public int Version { get; set; }

    [Column(TypeName = "json")]
    public string JsonContent { get; set; } = null!;

    [StringLength(20)]
    public string Status { get; set; } = null!;

    public DateTime? CreatedAt { get; set; }

    [StringLength(100)]
    public string? CreatedBy { get; set; }
}